name: 'Helmfile Deploy'
description: 'Sync Helmfile to Kubernetes cluster.'
inputs:
  vault:
    description: 'Token to login to Vault to access secrets.'
    required: true
  kubeconfig:
    description: 'KUBECONFIG for cluster to deploy to'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    VAULT_TOKEN: ${{ inputs.vault }}
    KUBECONFIG: ${{ inputs.kubeconfig }}