name: 'Docker Build or Push'
description: 'Build docker image and push to registry in case of push or release.'
inputs:
  push:
    description: 'Weather or not to push built image to registry.'
    default: 'false'
    required: false
  tag:
    description: 'Docker image tag.'
    required: false
  registry:
    description: 'Server address of Docker registry. If not set then will default to Docker Hub'
    required: false
  username:
    description: 'Username used to log against the Docker registry'
    required: false
  password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        registry: ${{inputs.registry}}
        username: ${{inputs.username}}
        password: ${{inputs.password}}
    - uses: docker/build-push-action@v2
      with:
        push: ${{inputs.push}}
        tags: ${{inputs.tag}}
