name: 'Docker Build or Push'
description: 'Build docker image and push to Artifactory in case of push or release.'
inputs:
  artifactory:
    description: 'Location to push the image to in Artifactory'
    required: false
    default: artifactory.build.ingka.ikea.com/ushub-docker-dev-local
  secrets:
    description: 'Pipeline secrets (Artifactory username/password and GitHub username/token)'
    required: true
  cache:
    description: 'To enable caching, pass in cache directory here.'
    required: false
outputs:
  environment:
    description: 'Name of which environment(s) to deploy to.'
    value: ${{ steps.set-env.outputs.environment }}
runs:
  using: 'composite'
  steps:
    - name: Docker build or Push
      run: |
        [[ -n "${{ inputs.cache }}" ]] && mkdir -p "${{ inputs.cache }}"
        mnt=$([[ -n "${{ inputs.cache }}" ]] && echo "--volume=${{ inputs.cache }}:${{ inputs.cache }}" || echo "")
        echo "$mnt"
        docker build -t docker-build "${{ github.action_path }}"
        docker run -v /var/run/docker.sock:/var/run/docker.sock \
        -e ARTIFACTORY -e SECRETS -e GITHUB_EVENT_NAME -e GITHUB_REF \
        -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_TOKEN \
        "$mnt" \
        docker-build
      shell: bash
      env:
        ARTIFACTORY: ${{ inputs.artifactory }}
        SECRETS: ${{ inputs.secrets }}
        CACHE: ${{ inputs.cache }}