name: Publish Docker Image

on:
  release:
    types: [released]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker-build
        uses: docker/build-push-action@v2
        with:
          context: images/docker-build
          push: true
          tags: almed4/docker-build:latest,almed4/docker-build:${GITHUB_REF##*/}

      - name: Build and push helm-deploy
        uses: docker/build-push-action@v2
        with:
          context: images/helm-deploy
          push: true
          tags: almed4/helm-deploy:latest,almed4/helm-deploy:${GITHUB_REF##*/}